config/routes.rb
Rails.application.routes.draw do

  get "profile" => "users#show", :as => 'profile'

  resources :wikis

  devise_for :users

  root 'welcome#index'

  resources :charges, only: [:new, :create]

  post "users/downgrade" => 'users#downgrade', :as => 'downgrade_user'

  resources :collaborators, only: [:create, :destroy]


end

app/models/amount.rb
class Amount
  def self.default
    DEFAULT_PRICE
  end

  DEFAULT_PRICE = 15_00
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user

  validates :user_id, presence: true
  validates :wiki_id, presence: true

  after_create :send_collaborator_email

  private
  def send_collaborator_email
    CollaboratorMailer.new_collaborator(self).deliver_now
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify :after_add => :email_premium_user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis
  has_many :collaborators, dependent: :destroy

  after_initialize :set_role

  include FriendlyId
  friendly_id :username, use: :slugged

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def downgrade
    self.remove_role :premium
  end

  private

  def set_role
    self.add_role :standard
  end

  def email_premium_user(user)
    if self.is_premium?
      PremiumMailer.premium_upgrade(self).deliver_now
    end
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
  resourcify

  scope :publicly_viewable, -> { where( private: false ) }
  scope :privately_viewable, -> { where( private: true ) }
  scope :visible_to, -> ( user ) { user && (user.is_admin? || user.is_premium?) ? all : publicly_viewable }

  include FriendlyId
  friendly_id :title, use: :slugged

  def self.search(search = nil)
    if search
      (self.where('title ILIKE ?', "%#{search}%").concat(self.where('body ILIKE ?', "%#{search}%")))
    else
      self.all
    end
  end

  def downgrade
    self.update(private: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :resource_name, :resource, :devise_mapping
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def after_sign_in_path_for(resource)
    profile_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || wikis_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_premium

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Premium Wikibloc Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.add_role :premium
    flash[:notice] = "Thank you for becoming a premium Wikibloc member! You may now create private wikis!"
    redirect_to profile_path

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
  end

  private

  def check_if_premium
    if current_user.is_premium?
      flash[:notice] = "You are already a premium member!"
      redirect_to profile_path
    end
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    wiki = Wiki.find(params[:wiki])
    email = params[:collaborators_email]
    user = User.find_by(email: email)

    collaborator = wiki.collaborators.new(user: user)

    if collaborator.save
      flash[:notice] = "Collaborator Added."
    else
      flash[:alert] = "Could not find a user with that email address. Please try again"
    end
    redirect_to wiki
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    @wiki = @collaborator.wiki

    if @collaborator.destroy
      flash[:notice] = "\"#{@collaborator.user.username}\" is no longer a collaborator."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error removing this collaborator. Please try again."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(current_user.id)
  end

  def downgrade
    @user = current_user
    @user.downgrade
    @user.wikis.each { |wiki| wiki.downgrade }

    flash[:notice] = "You now have standard access."
    redirect_to profile_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!
  def index
    @wikis =  policy_scope(Wiki)
    @wikis = Wiki.where(id: @wikis.map(&:id))
    @wikis = @wikis.search(params[:search])

  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    authorize @wiki
    @wiki = current_user.wikis.build(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was saved successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was saved successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to profile_path
    else
      flash.now[:alert] = "There was an error deleting the post. Please try again."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(policy(@wiki).permitted_attributes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer    = Redcarpet::Render::HTML.new(options)
    @markdown ||= Redcarpet::Markdown.new(renderer, extensions)
    
    @markdown.render(text).html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/_new_charge.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>$15.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Premium Wikibloc Membership - #{current_user.username}"
          data-amount="<%= Amount.default %>"
          data-locale="auto">
  </script>
<% end %>

app/views/charges/new.html.erb
<div class="container">
  <div class="authform" style="text-align: center;">
    <h4>Upgrade to Premium!</h4>
    <%= render partial: 'new_charge' %>
  </div>
</div>

app/views/collaborators/_form.html.erb
<%= form_for [collaborator, wiki], url: collaborators_path, method: :post do |f| %>

  <div class='form-group'>
    <%= f.label :add_collaborator %>
    <%= email_field_tag :collaborators_email,
                     params[:collaborators_email],
                     class: 'form-control',
                     placeholder: "Collaborator's email address"
                     %>
    <%= hidden_field_tag :wiki, wiki.id %>

  </div>

  <div class="form-group">
    <%= f.submit "Add",class: "btn btn-success btn-lrg" %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikibloc</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% if user_signed_in? %>
          <a class="navbar-brand" href="/profile">Wikibloc</a>
        <% else %>
          <a class="navbar-brand" href="/">Wikibloc</a>
        <% end %>
      </div>

      <div class="navbar-collapse collapse navbar-left">
        <ul class="nav navbar-nav">
          <li>
            <a href="/wikis">All Wikis</a>
          </li>
        </ul>
      </div>
      <div id="navbar" class="navbar-collapse collapse navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">Signed in as <%= current_user.username %></p>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'btn btn-default navbar-btn' %>
        <% else %>
          <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => { :role => 'form'}) do |f| %>
            <div class="navbar-form navbar-right">
              <div class="form-group">
                <%= f.email_field :email, class: 'form-control', placeholder: 'Email Address' %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
              </div>
              <button type="submit" class="btn btn-default">Sign in</button>
            </div>
          <% end %>
        <% end %>
      </div><!--/.navbar-collapse -->
    </div>
  </nav>

  <!-- <div class="container"> -->
    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
        <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
  <!-- </div> -->

  <!-- <div class="container"> -->
    <%= yield %>
  <!-- </div> -->


</body>
</html>

app/views/users/show.html.erb
<div class="container col-md-10 col-md-offset-1">
  <br />
  <h2 class="media-heading">Welcome, <%= @user.username %>!</h2>

  <div class ="row">
    <div class="col-md-9">
      <div class="row vertical-align">
        <div class="col-md-6">
          <h3 class="pull-left">Your Wikis</h3>
        </div>
        <div class="col-md-6">
          <span class="pull-right">
            <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-info' %>
          </span>
        </div>
      </div>

      <div class="list-group">
        <% @user.wikis.each do |wiki| %>
          <a href="<%= wiki_path(wiki.id) %>" class="list-group-item">
            <% if wiki.private %>
              <span class="badge">private</span>
            <% end %>
            <%= wiki.title %>
          </a>
        <% end %>

        <% @user.collaborators.map(&:wiki).each do |wiki| %>
          <a href="<%= wiki_path(wiki.id) %>" class="list-group-item">
            <% if wiki.private %>
              <span class="badge">private</span>
            <% end %>
            <%= wiki.title %>
          </a>
        <% end %>
      </div>
    </div>

    <div class="col-md-3" id="user-info">
      <% avatar_url = @user.avatar_url(200) %>
      <% if avatar_url %>
        <figure>
          <%= image_tag avatar_url, class: "media-object img-rounded center-block" %>
          <figcaption  style="text-align:center;"><small><a href="http://gravatar.com">Change your avatar.</a></small></figcaption>
        </figure>
      <% end %>

      <div>
        <% if @user.is_premium? %>
          <h5 style="text-align:center;">Hey, thanks for being a premium user!  You may create your own private wikis.</h5>
          <p style="text-align:center;">If you wish to no longer be a premium user, you may downgrade account. Your private wikis will then become public.</p>
          <%= link_to "Downgrade", downgrade_user_path, method: :post, class: "btn btn-danger center-block", data: {confirm: "Are you sure you want to downgrade your account? All your private wikis will be made public!"} %>
        <% else %>
          <h5 style="text-align:center;">Not a premium member? Upgrade today to create your own private wiki where YOU choose your collaborators!</h5>
          <div style="text-align:center;">
            <%= render partial: 'charges/new_charge' %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Wikibloc</h1>
  <p>Stop. Collaborate and wiki.</p>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h3>Free to Use.</h3>
      <p>Sign up today to start your own wikis and collaborate with others to create a one-stop doc for shared info!</p>
    </div>
    <div class="col-md-3">
      <h3>Premium Access.</h4>
      <p>As a premium member, create and manage unlimited private wikis.</p>
    </div>
    <div class="col-md-6">
      <%= render partial: 'devise/registrations/sign_up' %>
    </div>
  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: "form-control" %>
  </div>

  <% if current_user.is_admin? || current_user.is_premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Make Private
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit "Save",class: "btn btn-success btn-lrg" %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Edit Wiki</h1>
      <h5>Wikibloc accepts <a href="http://assemble.io/docs/Cheatsheet-Markdown.html">Markdown syntax</a></h5><br />
      <%= render partial: 'form', locals: { wiki: @wiki } %>
    </div>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <div class="row vertical-align">
        <div class="col-md-6">
          <h1 class="pull-left">Wikis</h1>
        </div>
        <div class="col-md-6">
          <span class="pull-right">
            <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-info' %>
          </span>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <%= form_tag wikis_path, method: :get do %>
            <div class="form-group">
              <div class="input-group">
                <%= text_field_tag :search, params[:search], class: "form-control" %>
                  <span class="input-group-btn">
                    <%= submit_tag "Search", name: nil, class: 'btn btn-default' %>
                  </span>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="list-group">
            <% @wikis.each do |wiki| %>
              <a href="<%= wiki_path(wiki.id) %>" class="list-group-item">
                <% if wiki.private %>
                  <span class="badge">private</span>
                <% end %>
                <%= wiki.title %>
              </a>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/wikis/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Create a new Wiki</h1>
      <h5>Wikibloc accepts <a href="http://assemble.io/docs/Cheatsheet-Markdown.html">Markdown syntax</a></h5><br />
      <%= render partial: 'form', locals: { wiki: @wiki } %>
    </div>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1><%= markdown(@wiki.title) %></h1>
      <p><%= markdown(@wiki.body) %></p>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: "btn btn-success" %>
      <% if policy(@wiki).destroy? %>
        <%= link_to "Delete Wiki", @wiki, method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure you want to delete this wiki?"} %>
      <% end %>
    </div>
  </div>

  <% if @wiki.private %>
    <div class="col-md-8 col-md-offset-2">
      <div class="row">
        <h3>Collaborators:</h3>
      </div>

      <div class="row">
        <div class="list-group">
          <% @wiki.collaborators.each do |collaborator| %>
            <p class="list-group-item">
              <%= collaborator.user.username %>
              <%= link_to raw('<span class="label label-danger pull-right">Remove</span>'), collaborator, method: :delete, data: {confirm: "Are you sure you want to remove this collaborator?"} %>
            </p>
          <% end %>
        </div>
      </div>

      <div class="row">
        <%= render 'collaborators/form', collaborator: Collaborator.new, wiki: @wiki %>
      </div>
    </div>
  <% end %>

</div>